;
; File generated by cc65 v 2.14.0
;
	.fopt		compiler,"cc65 v 2.14.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_col
	.import		_ppu_on_all
	.import		_vram_adr
	.import		_vram_put
	.export		_put_str
	.export		_main

.segment	"RODATA"

L0021:
	.byte	$49,$20,$42,$45,$54,$20,$59,$4F,$55,$20,$44,$49,$44,$4E,$27,$54
	.byte	$20,$45,$58,$50,$45,$43,$54,$20,$54,$48,$49,$53,$2E,$00
L0019:
	.byte	$48,$45,$4C,$4C,$4F,$2C,$20,$4B,$45,$4E,$20,$42,$52,$45,$57,$45
	.byte	$52,$21,$00
L0029:
	.byte	$42,$55,$54,$20,$48,$45,$52,$45,$20,$49,$54,$20,$49,$53,$21,$00
L0031:
	.byte	$20,$20,$20,$20,$48,$45,$4C,$4C,$4F,$20,$4E,$45,$53,$21,$00

; ---------------------------------------------------------------
; void __near__ put_str (unsigned int, __near__ const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_put_str: near

.segment	"CODE"

;
; vram_adr(adr);
;
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _vram_adr
;
; if(!*str) break;
;
L0004:	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1),y
	beq     L0005
;
; vram_put((*str++)-0x20);//-0x20 because ASCII code 0x20 is placed in tile 0 of the CHR
;
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L000D
	inx
L000D:	jsr     stax0sp
	ldy     #$00
	lda     (regsave),y
	sec
	sbc     #$20
	jsr     _vram_put
;
; while(1)
;
	jmp     L0004
;
; }
;
L0005:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; pal_col(1,0x03);//set while color
;
	lda     #$01
	jsr     pusha
	lda     #$03
	jsr     _pal_col
;
; put_str(NTADR(0,2),"HELLO, KEN BREWER!");
;
	jsr     decsp4
	lda     #$40
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$20
	sta     (sp),y
	lda     #<(L0019)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0019)
	sta     (sp),y
	jsr     _put_str
;
; put_str(NTADR(2,3),"I BET YOU DIDN'T EXPECT THIS.");
;
	jsr     decsp4
	lda     #$62
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$20
	sta     (sp),y
	lda     #<(L0021)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0021)
	sta     (sp),y
	jsr     _put_str
;
; put_str(NTADR(2,5),"BUT HERE IT IS!");
;
	jsr     decsp4
	lda     #$A2
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$20
	sta     (sp),y
	lda     #<(L0029)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0029)
	sta     (sp),y
	jsr     _put_str
;
; put_str(NTADR(2,6),"    HELLO NES!");
;
	jsr     decsp4
	lda     #$C2
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$20
	sta     (sp),y
	lda     #<(L0031)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L0031)
	sta     (sp),y
	jsr     _put_str
;
; ppu_on_all();//enable rendering
;
	jsr     _ppu_on_all
;
; while(1);//do nothing, infinite loop
;
L0038:	jmp     L0038

.endproc

